import { Github, HeartHandshake, LockKeyhole, Scale } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageShell } from '../components/PageShell'
import { usePageMeta } from '../hooks/usePageMeta'

export default function AboutPage() {
  usePageMeta('About This Project', 'About the open, static, privacy-friendly AI DevOps Field Guide and its editorial principles.')
  return <PageShell eyebrow="Open knowledge project" title="A grounded guide for the role transition" description="This project helps DevOps engineers learn AI reasoning, retrieval, agent workflows, and safe automation without framing experience as obsolete."><section className="container-shell section-pad"><div className="grid gap-4 md:grid-cols-3"><Value icon={<Scale />} title="Balanced" body="Benefits sit beside risks, counterarguments, and production boundaries." /><Value icon={<LockKeyhole />} title="Private by design" body="Progress, ratings, votes, assessment results, and preferences stay on your device." /><Value icon={<HeartHandshake />} title="Community editable" body="GitHub issues and pull requests are the contribution workflow—no account system is embedded." /></div><div className="mt-12 grid gap-8 lg:grid-cols-2"><div><h2 className="title-md">Editorial principle</h2><p className="muted mt-4 leading-7">AI should recommend and reason from evidence. Controlled deterministic tools should perform changes. Human accountability, least privilege, policy, rollback, and verification remain central.</p></div><div className="rounded-2xl bg-[var(--navy)] p-7 text-white"><p className="eyebrow">Product message</p><p className="mt-4 text-xl font-semibold leading-8">DevOps expertise × AI reasoning × knowledge retrieval × controlled automation × human approval × verification.</p></div></div><div className="mt-12 flex flex-wrap gap-3"><Link className="btn-primary" to="/roadmap">Start the roadmap</Link><a className="btn-secondary" href="https://github.com/arvindr226/sample-website" target="_blank" rel="noreferrer"><Github size={17} /> GitHub repository</a></div></section></PageShell>
}

function Value({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <article className="panel p-6"><span className="text-[var(--accent-dark)]">{icon}</span><h2 className="mt-5 font-bold">{title}</h2><p className="muted mt-2 text-sm leading-6">{body}</p></article> }
