import { ArrowLeft, ArrowRight, Check, RotateCcw, ShieldCheck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { PageShell } from '../components/PageShell'
import { StatusBar } from '../components/StatusBar'
import { assessmentQuestions, responseOptions } from '../data/assessment'
import { usePageMeta } from '../hooks/usePageMeta'
import { calculateAssessmentScores, readinessBand } from '../utils/assessment'
import { readStorage, STORAGE_KEYS, writeStorage, type AssessmentRecord } from '../utils/storage'

export default function AssessmentPage() {
  const previous = readStorage<AssessmentRecord | null>(STORAGE_KEYS.assessment, null)
  const [answers, setAnswers] = useState<Record<string, number>>(previous?.answers ?? {})
  const [step, setStep] = useState(previous ? Number.MAX_SAFE_INTEGER : 0)
  const groups = useMemo(() => [...new Set(assessmentQuestions.map(question => question.category))].map(category => ({ category, questions: assessmentQuestions.filter(question => question.category === category) })), [])
  const [result, setResult] = useState<AssessmentRecord | null>(previous)
  usePageMeta('AI DevOps Readiness Assessment', 'A private 25-question, client-side assessment across DevOps, Kubernetes, programming, AI, RAG, agents, and safety.')
  const current = groups[step]
  const answered = Object.keys(answers).length
  const submit = () => { const scores = calculateAssessmentScores(answers); const record = { completedAt: new Date().toISOString(), answers, scores: scores.categories, overall: scores.overall }; writeStorage(STORAGE_KEYS.assessment, record); setResult(record); setStep(groups.length) }
  const restart = () => { setAnswers({}); setResult(null); setStep(0) }
  return <PageShell eyebrow="Private, client-side assessment" title="How ready are you for AI DevOps?" description="Twenty-five questions across seven capability groups. Nothing leaves your browser and no account is required."><section className="container-shell section-pad">{step < groups.length && current ? <div className="mx-auto max-w-3xl"><div className="mb-8"><div className="flex justify-between text-sm"><span className="font-bold">{current.category}</span><span className="muted">{answered}/25 answered</span></div><div className="mt-3"><StatusBar value={((step + 1) / groups.length) * 100} label={`Section ${step + 1} of ${groups.length}`} /></div></div><div className="space-y-5">{current.questions.map((question, questionIndex) => <fieldset className="panel p-5 md:p-6" key={question.id}><legend className="px-1 text-sm font-bold leading-6"><span className="mr-2 font-mono text-[var(--accent-dark)]">{String(assessmentQuestions.indexOf(question) + 1).padStart(2, '0')}</span>{question.question}</legend><div className="mt-4 grid gap-2 sm:grid-cols-3">{responseOptions.map(option => <label className={`cursor-pointer rounded-lg border p-3 ${answers[question.id] === option.value ? 'border-[var(--accent)] bg-[color-mix(in_srgb,var(--accent)_8%,var(--surface))]' : 'border-[var(--line)]'}`} key={option.value}><input type="radio" className="sr-only" name={question.id} value={option.value} checked={answers[question.id] === option.value} onChange={() => setAnswers(currentAnswers => ({ ...currentAnswers, [question.id]: option.value }))} /><span className="flex items-center gap-2 text-sm font-bold">{answers[question.id] === option.value && <Check size={15} />}{option.label}</span><span className="muted mt-1 block text-xs leading-5">{option.help}</span></label>)}</div>{questionIndex === current.questions.length - 1 && <p className="sr-only">Last question in this section</p>}</fieldset>)}</div><div className="mt-8 flex items-center justify-between"><button className="btn-secondary" disabled={step === 0} onClick={() => setStep(value => Math.max(0, value - 1))}><ArrowLeft size={16} /> Previous</button>{step < groups.length - 1 ? <button className="btn-primary" disabled={current.questions.some(question => answers[question.id] === undefined)} onClick={() => setStep(value => value + 1)}>Next section <ArrowRight size={16} /></button> : <button className="btn-primary" disabled={assessmentQuestions.some(question => answers[question.id] === undefined)} onClick={submit}>Calculate readiness <ArrowRight size={16} /></button>}</div></div> : result ? <Results result={result} onRestart={restart} /> : null}</section></PageShell>
}

function Results({ result, onRestart }: { result: AssessmentRecord; onRestart: () => void }) {
  const band = readinessBand(result.overall)
  const ordered = Object.entries(result.scores).sort((a, b) => b[1] - a[1])
  const strong = ordered.filter(([, score]) => score >= 70)
  const focus = ordered.filter(([, score]) => score < 70).sort((a, b) => a[1] - b[1]).slice(0, 3)
  return <div className="mx-auto max-w-4xl"><div className="rounded-2xl bg-[var(--navy)] p-7 text-white md:grid md:grid-cols-[auto_1fr] md:items-center md:gap-8"><div className="grid h-36 w-36 place-items-center rounded-full border-[10px] border-emerald-400/25 bg-slate-900"><div className="text-center"><span className="block text-4xl font-bold text-emerald-300">{result.overall}%</span><span className="text-xs text-slate-400">Overall</span></div></div><div className="mt-6 md:mt-0"><p className="eyebrow">AI DevOps readiness</p><h2 className="title-md mt-3">{band.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{band.detail}</p><p className="mt-4 text-xs text-slate-500">Saved locally {new Date(result.completedAt).toLocaleString()}</p></div></div><div className="mt-8 grid gap-5 md:grid-cols-2"><div className="panel p-6"><h2 className="font-bold">Capability scores</h2><div className="mt-5 space-y-5">{ordered.map(([category, score]) => <StatusBar value={score} label={category} key={category} />)}</div></div><div className="space-y-5"><div className="panel p-6"><h2 className="font-bold text-[var(--accent-dark)]">Strong areas</h2><ul className="mt-4 space-y-2 text-sm">{strong.length ? strong.map(([category, score]) => <li key={category}>• {category} — {score}%</li>) : <li>Build the foundations first; every category can improve.</li>}</ul></div><div className="panel p-6"><h2 className="font-bold text-amber-600 dark:text-amber-300">Focus next</h2><ul className="mt-4 space-y-3">{focus.map(([category, score]) => { const question = assessmentQuestions.find(item => item.category === category && (result.answers[item.id] ?? 0) < 2); return <li className="text-sm" key={category}><span className="font-bold">{category} ({score}%)</span><span className="muted mt-1 block">{question?.recommendation}</span></li> })}</ul></div><div className="rounded-xl border border-[color-mix(in_srgb,var(--accent)_45%,var(--line))] bg-[color-mix(in_srgb,var(--accent)_6%,var(--surface))] p-5"><p className="flex items-center gap-2 font-bold"><ShieldCheck size={17} /> Privacy note</p><p className="muted mt-2 text-xs leading-5">Answers and results remain in this browser. No data is transmitted.</p></div></div></div><button className="btn-secondary mt-8" onClick={onRestart}><RotateCcw size={16} /> Retake assessment</button></div>
}
