import { ArrowRight, Search, Star } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { BookmarkButton } from '../components/BookmarkButton'
import { PageShell } from '../components/PageShell'
import { blogCategories, blogs } from '../content/blogs'
import { usePageMeta } from '../hooks/usePageMeta'

export default function BlogsPage() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('all')
  const [sort, setSort] = useState<'latest' | 'rating' | 'popular'>('latest')
  usePageMeta('AI DevOps Blogs', 'Field notes on AI DevOps, Kubernetes agents, RAG, AIOps, observability, safety, and career transition.')
  const visible = useMemo(() => blogs.filter(blog => (category === 'all' || blog.category === category) && `${blog.title} ${blog.description} ${blog.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'rating' ? b.rating - a.rating : sort === 'popular' ? b.popularity - a.popularity : b.publishedDate.localeCompare(a.publishedDate)), [category, query, sort])
  const featured = blogs.find(blog => blog.featured)
  return <PageShell eyebrow="Engineering field notes" title="Ideas you can operate" description="Long-form, source-controlled guides for building useful AI operations systems without giving up engineering control."><section className="container-shell section-pad">{featured && <article className="mb-12 grid overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--navy)] text-white lg:grid-cols-[1.2fr_.8fr]"><div className="p-7 md:p-10"><p className="text-xs font-bold uppercase tracking-[.15em] text-emerald-300">Featured field note</p><h2 className="title-lg mt-4">{featured.title}</h2><p className="mt-5 max-w-2xl leading-7 text-slate-400">{featured.description}</p><Link className="btn-primary mt-7" to={`/blogs/${featured.slug}`}>Read the guide <ArrowRight size={17} /></Link></div><div className="grid place-items-center border-t border-slate-800 p-8 lg:border-l lg:border-t-0"><div className="w-full rounded-xl border border-slate-700 bg-slate-900 p-5 font-mono text-sm"><p className="text-emerald-300">field_note.load()</p><p className="mt-3 text-slate-400">category: {featured.category}</p><p className="text-slate-400">reading_time: {featured.readingTime}</p><p className="text-slate-400">editorial_rating: {featured.rating}/5</p></div></div></article>}
  <div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><label className="relative"><span className="sr-only">Filter blogs</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]" size={17} /><input className="h-12 w-full rounded-lg border border-[var(--line)] bg-[var(--surface)] pl-10 pr-3" placeholder="Search articles, tags, or topics" value={query} onChange={event => setQuery(event.target.value)} /></label><select aria-label="Filter by category" className="h-12 rounded-lg border border-[var(--line)] bg-[var(--surface)] px-3" value={category} onChange={event => setCategory(event.target.value)}><option value="all">All categories</option>{blogCategories.map(item => <option value={item} key={item}>{item}</option>)}</select><select aria-label="Sort blogs" className="h-12 rounded-lg border border-[var(--line)] bg-[var(--surface)] px-3" value={sort} onChange={event => setSort(event.target.value as typeof sort)}><option value="latest">Latest</option><option value="rating">Top rated</option><option value="popular">Most popular</option></select></div>
  <p className="muted my-6 text-sm">{visible.length} article{visible.length === 1 ? '' : 's'} · Popularity is author-configured static metadata.</p>{visible.length ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visible.map(blog => <article key={blog.slug} className="panel flex flex-col p-6"><div className="flex items-start justify-between gap-3"><span className="chip">{blog.category}</span><BookmarkButton compact item={{ id: blog.slug, type: 'blog', title: blog.title, path: `/blogs/${blog.slug}` }} /></div><h2 className="mt-5 text-xl font-bold leading-7"><Link to={`/blogs/${blog.slug}`} className="hover:text-[var(--accent-dark)]">{blog.title}</Link></h2><p className="muted mt-3 flex-1 text-sm leading-6">{blog.description}</p><div className="mt-5 flex flex-wrap gap-2">{blog.tags.slice(0, 3).map(tag => <span className="chip" key={tag}>{tag}</span>)}</div><div className="muted mt-6 flex items-center justify-between border-t border-[var(--line)] pt-4 text-xs"><span>{blog.readingTime}</span><span className="flex items-center gap-1"><Star size={13} fill="currentColor" className="text-amber-500" /> Editorial {blog.rating}</span></div></article>)}</div> : <div className="panel py-16 text-center"><Search className="mx-auto text-[var(--muted)]" /><h2 className="mt-4 text-xl font-bold">No field notes found</h2><p className="muted mt-2">Try a broader phrase or clear the category filter.</p><button className="btn-secondary mt-5" onClick={() => { setQuery(''); setCategory('all') }}>Clear filters</button></div>}</section></PageShell>
}
