import { ExternalLink, GitPullRequest } from 'lucide-react'
import { PageShell } from '../components/PageShell'
import { usePageMeta } from '../hooks/usePageMeta'

export default function ContributingPage() {
  usePageMeta('Contributing', 'Contribute blogs, discussions, tools, case studies, roadmap improvements, and corrections through GitHub pull requests.')
  const contributions = [['Add a blog', 'Create a Markdown article with complete frontmatter in src/content/blogs.'], ['Add a discussion', 'Add a balanced, typed entry with arguments, risks, and architecture.'], ['Add a tool', 'Provide neutral description, source URL, use cases, and clearly editorial ratings.'], ['Add a case study', 'Document problem, architecture, risk, approval boundary, and lessons.'], ['Improve the roadmap', 'Keep prerequisites, effort, resources, and relationships practical.'], ['Fix content', 'Use the content correction issue template for focused changes.']]
  return <PageShell eyebrow="GitHub is the community layer" title="Contribute through issues and pull requests" description="No embedded forum or database is required. The repository preserves review, attribution, history, and discussion."><section className="container-shell section-pad"><div className="grid gap-4 md:grid-cols-2">{contributions.map(([title, detail]) => <article className="panel p-6" key={title}><h2 className="font-bold">{title}</h2><p className="muted mt-2 text-sm leading-6">{detail}</p></article>)}</div><div className="mt-10 rounded-2xl bg-[var(--navy)] p-7 text-white"><GitPullRequest className="text-emerald-300" /><h2 className="title-md mt-4">Contribution workflow</h2><ol className="mt-5 grid gap-3 text-sm text-slate-300 sm:grid-cols-4"><li>01 · Open or choose an issue</li><li>02 · Fork and edit static content</li><li>03 · Run checks locally</li><li>04 · Submit a focused pull request</li></ol><a className="btn-primary mt-7" href="https://github.com/arvindr226/sample-website/blob/main/CONTRIBUTING.md" target="_blank" rel="noreferrer">Read contributor guide <ExternalLink size={16} /></a></div></section></PageShell>
}
