import { ArrowDown, Scale, ShieldCheck } from 'lucide-react'
import { PageShell } from '../components/PageShell'
import { debates } from '../data/debates'
import { usePageMeta } from '../hooks/usePageMeta'

export default function DebatesPage() {
  usePageMeta('AI DevOps Debates', 'Balanced arguments for and against controversial AI operations practices, with a human-controlled middle path.')
  return <PageShell eyebrow="Balanced viewpoints" title="Good engineering lives between the extremes" description="Each debate names the opportunity, the failure modes, and a practical human-in-the-loop architecture."><section className="container-shell section-pad space-y-8">{debates.map(debate => <article className="overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--surface)]" key={debate.slug}><header className="border-b border-[var(--line)] p-6 md:p-8"><p className="eyebrow">{debate.category}</p><h2 className="title-md mt-3">{debate.title}</h2></header><div className="grid md:grid-cols-2"><div className="border-b border-[var(--line)] p-6 md:border-b-0 md:border-r md:p-8"><p className="font-bold text-emerald-700 dark:text-emerald-300">FOR</p><ul className="mt-4 space-y-3">{debate.for.map(item => <li className="text-sm">+ {item}</li>)}</ul></div><div className="p-6 md:p-8"><p className="font-bold text-rose-700 dark:text-rose-300">AGAINST</p><ul className="mt-4 space-y-3">{debate.against.map(item => <li className="text-sm">− {item}</li>)}</ul></div></div><div className="border-t border-[var(--line)] bg-[var(--surface-soft)] p-6 md:p-8"><p className="flex items-center gap-2 font-bold"><Scale size={18} className="text-[var(--accent-dark)]" /> Human-in-the-loop approach</p><p className="muted mt-3 max-w-4xl text-sm leading-6">{debate.middle}</p></div></article>)}<div className="rounded-2xl bg-[var(--navy)] p-7 text-white"><ShieldCheck className="text-emerald-300" /><h2 className="title-md mt-4">Recommended remediation architecture</h2><div className="mt-7 grid gap-2 sm:grid-cols-4">{['AI identifies issue', 'Plan + evidence', 'Policy validation', 'Human approval', 'Deterministic execution', 'Independent verification', 'Rollback if needed', 'Operational memory'].map((step, index) => <div key={step} className="flex items-center gap-2"><div className="flex-1 rounded-lg border border-slate-700 bg-slate-900 p-3 text-center text-xs font-bold">{step}</div>{index < 7 && <ArrowDown className="hidden text-slate-600 sm:block sm:-rotate-90" size={14} />}</div>)}</div></div></section></PageShell>
}
