import { ArrowDown, ArrowRight, BookOpen, Bot, CheckCircle2, CircleGauge, GitPullRequestArrow, Radar, ShieldCheck, Sparkles, TerminalSquare } from 'lucide-react'
import { Link } from 'react-router-dom'
import { blogs } from '../content/blogs'
import { caseStudies } from '../data/caseStudies'
import { discussions } from '../data/discussions'
import { roadmap } from '../data/roadmap'
import { tools } from '../data/tools'
import { usePageMeta } from '../hooks/usePageMeta'

const traditional = ['Linux', 'Networking', 'Docker', 'CI/CD', 'Cloud', 'Terraform', 'Kubernetes', 'Helm', 'GitOps', 'Monitoring']
const aiDevOps = ['Python', 'LLMs', 'Prompt engineering', 'Embeddings', 'Vector search', 'RAG', 'AI agents', 'LangGraph', 'MCP', 'Tool calling', 'AIOps', 'Automated RCA', 'Operational memory']
const highlights = [
  { icon: CircleGauge, label: 'Interactive roadmap', value: '9 stages', text: 'Progress from Linux and Kubernetes to RAG, agents, guardrails, and operational memory.', href: '/roadmap' },
  { icon: BookOpen, label: 'Featured field note', value: 'RAG for DevOps', text: 'Turn runbooks, incidents, and platform docs into grounded operational context.', href: '/blogs/rag-explained-for-devops' },
  { icon: ShieldCheck, label: 'Production principle', value: 'Control before autonomy', text: 'Let AI reason and recommend. Let deterministic, policy-checked tools execute.', href: '/architecture' },
]

export default function HomePage() {
  usePageMeta('From DevOps Engineer to AI DevOps Engineer', 'Understand how AI, agentic systems, RAG, and controlled automation are transforming DevOps.')
  return <main><section className="relative overflow-hidden border-b border-[var(--line)] bg-[var(--surface)]"><div className="grid-lines pointer-events-none absolute inset-0 opacity-50" /><div className="container-shell relative grid min-h-[690px] items-center gap-12 py-20 lg:grid-cols-[1.2fr_.8fr]"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-[var(--bg)] px-3 py-1.5 text-xs font-bold text-[var(--muted)]"><span className="h-2 w-2 rounded-full bg-[var(--accent)]" />THE OPERATIONS ROLE IS EVOLVING</div><h1 className="display max-w-4xl">From DevOps Engineer to <span className="text-[var(--accent-dark)]">AI DevOps Engineer</span></h1><p className="muted mt-7 max-w-2xl text-lg leading-8 md:text-xl">Understand how AI, Agentic Systems, RAG and intelligent automation are transforming DevOps—without losing operational judgment, safety, or control.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="btn-primary" to="/roadmap">Explore the AI DevOps Roadmap <ArrowRight size={17} /></Link><Link className="btn-secondary" to="/discussions">Join the discussion</Link></div></div><div className="panel overflow-hidden shadow-[0_30px_80px_rgba(3,12,18,.12)]"><div className="flex items-center gap-2 border-b border-[var(--line)] px-4 py-3"><span className="h-2.5 w-2.5 rounded-full bg-red-400" /><span className="h-2.5 w-2.5 rounded-full bg-amber-400" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-400" /><span className="ml-2 font-mono text-[.65rem] text-[var(--muted)]">incident/checkout-latency</span></div><div className="space-y-5 p-5 font-mono text-sm"><div><span className="text-[var(--muted)]">09:42:06</span> <span className="text-red-500">ALERT</span> p95 latency &gt; 2.1s</div><div className="ml-4 border-l border-[var(--line)] pl-4"><p className="text-[var(--accent-dark)]">observability_agent.analyze()</p><p className="muted mt-1">Correlating metrics, events, traces…</p></div><div className="ml-4 border-l border-[var(--line)] pl-4"><p className="text-[var(--accent-dark)]">knowledge.retrieve()</p><p className="muted mt-1">Runbook match: DB pool exhaustion</p></div><div className="rounded-lg bg-[var(--surface-soft)] p-4"><p className="mb-2 flex items-center gap-2 font-sans font-bold"><Sparkles size={16} /> Suggested plan</p><p className="muted leading-6">Scale connection pool to 40, canary one pod, verify error budget and rollback if saturation persists.</p></div><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-xs text-amber-600 dark:text-amber-300"><ShieldCheck size={15} /> HUMAN APPROVAL REQUIRED</span><span className="rounded bg-[var(--accent)] px-3 py-1.5 font-sans text-xs font-bold text-[#031710]">Review plan</span></div></div></div></div></section>
  <section className="container-shell section-pad"><p className="eyebrow">The transition map</p><h2 className="title-lg mt-3 max-w-3xl">Keep the foundation. Add an intelligence layer.</h2><div className="mt-10 grid items-stretch gap-4 lg:grid-cols-[1fr_auto_1fr]"><div className="panel p-6"><div className="mb-6 flex items-center gap-3"><TerminalSquare className="text-[var(--muted)]" /><div><p className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Foundation</p><h3 className="title-md">DevOps Engineer</h3></div></div><div className="flex flex-wrap gap-2">{traditional.map(skill => <span key={skill} className="chip">{skill}</span>)}</div></div><div className="grid place-items-center py-2 text-[var(--accent-dark)]"><ArrowRight className="hidden lg:block" size={28} /><ArrowDown className="lg:hidden" size={28} /></div><div className="rounded-2xl border border-[color-mix(in_srgb,var(--accent)_45%,var(--line))] bg-[color-mix(in_srgb,var(--accent)_7%,var(--surface))] p-6"><div className="mb-6 flex items-center gap-3"><Bot className="text-[var(--accent-dark)]" /><div><p className="text-xs font-bold uppercase tracking-wider text-[var(--accent-dark)]">Extended practice</p><h3 className="title-md">AI DevOps Engineer</h3></div></div><div className="flex flex-wrap gap-2">{aiDevOps.map(skill => <span key={skill} className="chip">{skill}</span>)}</div></div></div></section>
  <section className="border-y border-[var(--line)] bg-[var(--navy)] text-white"><div className="container-shell section-pad"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Central architecture</p><h2 className="title-lg mt-3">Reason with AI.<br />Execute with control.</h2><p className="mt-5 max-w-lg leading-7 text-slate-400">AI DevOps is not “replace engineers with a chatbot.” It combines domain expertise, retrieved knowledge, bounded agent workflows, policy, approval, and verification.</p><Link to="/architecture" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-emerald-300">Study the architecture <ArrowRight size={16} /></Link></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{['Human intent', 'Context + RAG', 'Planner', 'Specialist agents', 'Policy checks', 'Human approval', 'Deterministic tools', 'Infrastructure', 'Verification'].map((step, index) => <div key={step} className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><span className="text-xs font-bold text-emerald-400">0{index + 1}</span><p className="mt-3 font-semibold">{step}</p></div>)}</div></div></div></section>
  <section className="container-shell section-pad"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Start here</p><h2 className="title-lg mt-3">A field guide, not a hype cycle.</h2></div><Link to="/search" className="btn-secondary">Search everything <ArrowRight size={16} /></Link></div><div className="mt-10 grid gap-4 md:grid-cols-3">{highlights.map(({ icon: Icon, label, value, text, href }) => <Link to={href} key={label} className="panel group p-6 transition-transform hover:-translate-y-1"><Icon className="text-[var(--accent-dark)]" size={24} /><p className="mt-8 text-xs font-bold uppercase tracking-wider text-[var(--muted)]">{label}</p><h3 className="mt-2 text-xl font-bold">{value}</h3><p className="muted mt-3 text-sm leading-6">{text}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[var(--accent-dark)]">Explore <ArrowRight className="transition-transform group-hover:translate-x-1" size={15} /></span></Link>)}</div></section>
  <section className="border-y border-[var(--line)] bg-[var(--surface)]"><div className="container-shell section-pad"><div className="grid gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Latest blogs</p><h2 className="title-md mt-3">Fresh from the field notes</h2></div><Link className="text-sm font-bold text-[var(--accent-dark)]" to="/blogs">View all →</Link></div><div className="mt-6 divide-y divide-[var(--line)] border-y border-[var(--line)]">{blogs.slice(0, 3).map(blog => <Link to={`/blogs/${blog.slug}`} className="group grid gap-3 py-5 sm:grid-cols-[7rem_1fr_auto] sm:items-center" key={blog.slug}><span className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">{blog.category}</span><span className="font-bold group-hover:text-[var(--accent-dark)]">{blog.title}</span><span className="text-xs text-[var(--muted)]">{blog.readingTime}</span></Link>)}</div></div><div><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Trending discussions</p><h2 className="title-md mt-3">Questions worth arguing well</h2></div><Link className="text-sm font-bold text-[var(--accent-dark)]" to="/discussions">View all →</Link></div><div className="mt-6 space-y-3">{[...discussions].sort((a, b) => b.importance - a.importance).slice(0, 3).map(item => <Link to={`/discussions/${item.slug}`} className="panel block p-4 hover:border-[var(--accent)]" key={item.slug}><span className="text-xs font-bold text-[var(--muted)]">{item.category} · Editorial importance {item.importance}</span><h3 className="mt-2 font-bold leading-6">{item.title}</h3></Link>)}</div></div></div></div></section>
  <section className="container-shell section-pad"><div className="grid gap-12 lg:grid-cols-[1fr_1fr]"><div><p className="eyebrow">Roadmap preview</p><h2 className="title-md mt-3">Nine stages, one coherent transition</h2><div className="mt-6 grid grid-cols-2 gap-3">{roadmap.slice(0, 6).map(stage => <Link className="panel p-4 hover:border-[var(--accent)]" to="/roadmap" key={stage.id}><span className="font-mono text-xs font-bold text-[var(--accent-dark)]">0{stage.number}</span><h3 className="mt-2 text-sm font-bold">{stage.title}</h3><p className="muted mt-1 text-xs">{stage.topics.length} topics</p></Link>)}</div><Link to="/roadmap" className="btn-primary mt-5">Open interactive roadmap <ArrowRight size={16} /></Link></div><div><p className="eyebrow">Popular tools</p><h2 className="title-md mt-3">A practical AI DevOps toolbox</h2><div className="mt-6 divide-y divide-[var(--line)] rounded-2xl border border-[var(--line)] bg-[var(--surface)]">{[...tools].sort((a, b) => b.relevance - a.relevance).slice(0, 6).map(tool => <div className="flex items-center justify-between gap-4 p-4" key={tool.slug}><div><h3 className="font-bold">{tool.name}</h3><p className="muted mt-1 text-xs">{tool.category} · {tool.useCases[0]}</p></div><span className="chip">Editorial {tool.editorialRating}</span></div>)}</div><Link to="/tools" className="btn-secondary mt-5">Compare tools <ArrowRight size={16} /></Link></div></div></section>
  <section className="border-t border-[var(--line)] bg-[var(--navy)] text-white"><div className="container-shell section-pad grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Featured case study</p><h2 className="title-lg mt-3">{caseStudies[0].title}</h2><p className="mt-5 leading-7 text-slate-400">{caseStudies[0].summary}</p><Link to={`/case-studies/${caseStudies[0].slug}`} className="btn-primary mt-7">Study the workflow <ArrowRight size={16} /></Link></div><div className="grid content-center gap-2 sm:grid-cols-3">{caseStudies[0].architecture.map((step, index) => <div className="rounded-lg border border-slate-800 bg-slate-900 p-4" key={step}><span className="text-xs font-bold text-emerald-400">{String(index + 1).padStart(2, '0')}</span><p className="mt-3 text-sm font-semibold">{step}</p></div>)}</div></div></section>
  <section className="border-t border-[var(--line)] bg-[var(--surface)]"><div className="container-shell section-pad grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="panel p-6"><Radar className="text-[var(--accent-dark)]" /><p className="eyebrow mt-6">Skill of the week</p><h2 className="mt-2 text-xl font-bold">Structured outputs</h2><p className="muted mt-3 text-sm leading-6">Move from prose answers to typed, validated plans your automation can safely inspect.</p></div><div className="panel p-6"><GitPullRequestArrow className="text-[var(--accent-dark)]" /><p className="eyebrow mt-6">Featured debate</p><h2 className="mt-2 text-xl font-bold">Should agents remediate production?</h2><p className="muted mt-3 text-sm leading-6">Speed matters. So do blast radius, approval, rollback, and proof of recovery.</p><Link to="/debates" className="mt-4 inline-block text-sm font-bold text-[var(--accent-dark)]">See both sides →</Link></div><div className="panel p-6"><CheckCircle2 className="text-[var(--accent-dark)]" /><p className="eyebrow mt-6">Career transition tip</p><h2 className="mt-2 text-xl font-bold">Build one grounded operator</h2><p className="muted mt-3 text-sm leading-6">A read-only Kubernetes triage assistant demonstrates more judgment than ten disconnected AI tutorials.</p><Link to="/learning-path" className="mt-4 inline-block text-sm font-bold text-[var(--accent-dark)]">Choose a track →</Link></div><div className="panel p-6"><BookOpen className="text-[var(--accent-dark)]" /><p className="eyebrow mt-6">Top rated content</p><h2 className="mt-2 text-xl font-bold">{blogs[0].title}</h2><p className="muted mt-3 text-sm leading-6">Editorial rating {blogs[0].rating}/5 · {blogs[0].readingTime}. Ratings are editorial, never presented as global votes.</p><Link to={`/blogs/${blogs[0].slug}`} className="mt-4 inline-block text-sm font-bold text-[var(--accent-dark)]">Read field note →</Link></div></div></section></main>
}
