import { Bookmark, CheckCircle2, ChevronDown, ChevronUp, Circle, Clock3 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { BookmarkButton } from '../components/BookmarkButton'
import { PageShell } from '../components/PageShell'
import { StatusBar } from '../components/StatusBar'
import { roadmap } from '../data/roadmap'
import { usePageMeta } from '../hooks/usePageMeta'
import type { ProgressState, RoadmapTopic } from '../types/content'
import { readRoadmapProgress, setRoadmapTopicProgress } from '../utils/storage'

const states: { value: ProgressState; label: string }[] = [{ value: 'not-started', label: 'Not started' }, { value: 'learning', label: 'Learning' }, { value: 'completed', label: 'Completed' }]

export default function RoadmapPage() {
  const [progress, setProgress] = useState(readRoadmapProgress)
  const [openTopic, setOpenTopic] = useState<string | null>(null)
  const [stageFilter, setStageFilter] = useState('all')
  usePageMeta('AI DevOps Roadmap', 'An interactive nine-stage transition roadmap from DevOps foundations to safe autonomous remediation concepts.')
  const allTopics = roadmap.flatMap(stage => stage.topics)
  const completed = allTopics.filter(item => progress[item.id] === 'completed').length
  const learning = allTopics.filter(item => progress[item.id] === 'learning').length
  const visible = stageFilter === 'all' ? roadmap : roadmap.filter(stage => stage.id === stageFilter)
  const percent = useMemo(() => allTopics.length ? (completed / allTopics.length) * 100 : 0, [allTopics.length, completed])

  const update = (id: string, state: ProgressState) => { setRoadmapTopicProgress(id, state); setProgress(current => ({ ...current, [id]: state })) }

  return <PageShell eyebrow="Interactive career map" title="The AI DevOps Roadmap" description="Progress is stored only in this browser. Move deliberately from reliable systems to grounded AI workflows, then earn autonomy through controls and evidence."><section className="container-shell section-pad"><div className="grid gap-5 lg:grid-cols-[1fr_18rem]"><div className="panel p-6"><div className="grid gap-6 sm:grid-cols-[1fr_auto]"><div><p className="eyebrow">Your local progress</p><h2 className="mt-2 text-2xl font-bold">{completed} of {allTopics.length} topics completed</h2></div><div className="flex gap-6 text-sm"><div><span className="block text-2xl font-bold text-[var(--accent-dark)]">{learning}</span><span className="muted">Learning</span></div><div><span className="block text-2xl font-bold">{Math.round(percent)}%</span><span className="muted">Complete</span></div></div></div><div className="mt-6"><StatusBar value={percent} label="Roadmap completion" /></div></div><label className="panel flex flex-col justify-center p-5 text-sm font-bold">Jump to stage<select className="mt-2 rounded-lg border border-[var(--line)] bg-[var(--surface)] p-2.5" value={stageFilter} onChange={event => setStageFilter(event.target.value)}><option value="all">All nine stages</option>{roadmap.map(stage => <option value={stage.id} key={stage.id}>{stage.number}. {stage.title}</option>)}</select></label></div>
  <div className="mt-10 space-y-6">{visible.map(stage => <section key={stage.id} className="grid gap-5 lg:grid-cols-[15rem_1fr]"><div><span className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-[var(--navy)] font-mono font-bold text-[var(--accent)]">{stage.number}</span><h2 className="mt-4 text-xl font-bold">{stage.title}</h2><p className="muted mt-2 text-sm leading-6">{stage.outcome}</p></div><div className="space-y-2">{stage.topics.map(item => <TopicRow item={item} state={progress[item.id] ?? 'not-started'} open={openTopic === item.id} onToggle={() => setOpenTopic(openTopic === item.id ? null : item.id)} onState={state => update(item.id, state)} key={item.id} />)}</div></section>)}</div></section></PageShell>
}

function TopicRow({ item, state, open, onToggle, onState }: { item: RoadmapTopic; state: ProgressState; open: boolean; onToggle: () => void; onState: (state: ProgressState) => void }) {
  return <article className="overflow-hidden rounded-xl border border-[var(--line)] bg-[var(--surface)]"><div className="flex flex-wrap items-center gap-3 p-4"><button onClick={onToggle} className="flex min-w-0 flex-1 items-center gap-3 border-0 bg-transparent text-left" aria-expanded={open}>{state === 'completed' ? <CheckCircle2 className="shrink-0 text-[var(--accent-dark)]" size={19} /> : <Circle className={state === 'learning' ? 'shrink-0 text-amber-500' : 'shrink-0 text-[var(--muted)]'} size={19} />}<span><span className="block font-bold">{item.title}</span><span className="muted mt-0.5 block text-xs">{item.difficulty} · {item.effort}</span></span></button><select aria-label={`Progress for ${item.title}`} className="rounded-lg border border-[var(--line)] bg-[var(--surface-soft)] px-2 py-2 text-xs font-bold" value={state} onChange={event => onState(event.target.value as ProgressState)}>{states.map(option => <option value={option.value} key={option.value}>{option.label}</option>)}</select><BookmarkButton compact item={{ id: item.id, type: 'roadmap', title: item.title, path: '/roadmap' }} /><button onClick={onToggle} className="grid h-9 w-9 place-items-center border-0 bg-transparent" aria-label={`${open ? 'Collapse' : 'Expand'} ${item.title}`}>{open ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</button></div>{open && <div className="border-t border-[var(--line)] bg-[var(--surface-soft)] p-5"><p className="leading-7">{item.description}</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><h3 className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Why it matters</h3><p className="mt-2 text-sm leading-6">{item.whyItMatters}</p></div><div><h3 className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Prerequisites</h3><p className="mt-2 text-sm leading-6">{item.prerequisites.length ? item.prerequisites.join(' · ') : 'No formal prerequisites'}</p></div><div><h3 className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Resources</h3><ul className="mt-2 space-y-1 text-sm">{item.resources.map(resource => <li key={resource}>• {resource}</li>)}</ul></div><div><h3 className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Learning effort</h3><p className="mt-2 flex items-center gap-2 text-sm"><Clock3 size={15} />{item.effort} · {item.difficulty}</p></div></div><div className="mt-5 flex flex-wrap gap-2"><span className="chip"><Bookmark size={13} /> Related blogs: {item.relatedBlogs.length}</span><span className="chip">Related discussions: {item.relatedDiscussions.length}</span></div></div>}</article>
}
