import { ArrowRight } from 'lucide-react'
import { PageShell } from '../components/PageShell'
import { skillMatrix } from '../data/skills'
import { usePageMeta } from '../hooks/usePageMeta'

export default function SkillsPage() {
  usePageMeta('AI DevOps Skills Matrix', 'Map durable DevOps capabilities to their AI DevOps extensions and practical outcomes.')
  return <PageShell eyebrow="Skills matrix" title="Extend what you already know" description="The transition is a set of adjacent capabilities—not a reset. Strong infrastructure judgment becomes the safety layer for AI-powered operations."><section className="container-shell section-pad"><div className="overflow-x-auto rounded-2xl border border-[var(--line)]"><table className="w-full min-w-[760px] border-collapse text-left"><thead><tr className="bg-[var(--navy)] text-white"><th className="p-4 text-xs uppercase tracking-wider">Traditional DevOps skill</th><th className="p-4 text-xs uppercase tracking-wider">Extension</th><th className="p-4 text-xs uppercase tracking-wider">Target depth</th><th className="p-4 text-xs uppercase tracking-wider">Engineering focus</th></tr></thead><tbody>{skillMatrix.map(([traditional, extension, level, focus], index) => <tr key={traditional} className={index % 2 ? 'bg-[var(--surface-soft)]' : 'bg-[var(--surface)]'}><td className="p-4 font-bold">{traditional}</td><td className="p-4"><span className="inline-flex items-center gap-2"><ArrowRight className="text-[var(--accent-dark)]" size={15} />{extension}</span></td><td className="p-4"><span className="chip">{level}</span></td><td className="muted p-4 text-sm">{focus}</td></tr>)}</tbody></table></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[['Beginner', 'Understand the concept and complete a guided lab.'], ['Intermediate', 'Build, test, and explain a focused integration.'], ['Advanced', 'Design for failure, policy, scale, and accountable production use.']].map(([level, detail]) => <div className="panel p-5" key={level}><p className="eyebrow">{level}</p><p className="muted mt-3 text-sm leading-6">{detail}</p></div>)}</div></section></PageShell>
}
