import { Check, ExternalLink, Scale, Search, Square } from 'lucide-react'
import { useMemo, useState } from 'react'
import { BookmarkButton } from '../components/BookmarkButton'
import { PageShell } from '../components/PageShell'
import { Rating } from '../components/Rating'
import { toolCategories, tools } from '../data/tools'
import { usePageMeta } from '../hooks/usePageMeta'

export default function ToolsPage() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('all')
  const [selected, setSelected] = useState<string[]>(['langgraph', 'langchain'])
  usePageMeta('AI DevOps Tool Directory', 'An editorial, vendor-neutral catalog of AI, agent, RAG, observability, Kubernetes, GitOps, IaC, security, and MLOps tools.')
  const visible = useMemo(() => tools.filter(tool => (category === 'all' || tool.category === category) && `${tool.name} ${tool.description} ${tool.useCases.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  const compared = tools.filter(tool => selected.includes(tool.slug))
  const toggle = (slug: string) => setSelected(current => current.includes(slug) ? current.filter(item => item !== slug) : current.length < 3 ? [...current, slug] : current)
  return <PageShell eyebrow="Static tool catalog" title="Choose tools by boundary, not buzz" description="Ratings express editorial judgment, not objective vendor rankings. Compare purpose, fit, and learning curve before adding another abstraction."><section className="container-shell section-pad"><div className="grid gap-3 md:grid-cols-[1fr_auto]"><label className="relative"><span className="sr-only">Search tools</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]" size={17} /><input className="h-12 w-full rounded-lg border border-[var(--line)] bg-[var(--surface)] pl-10 pr-3" placeholder="Search tools or use cases" value={query} onChange={event => setQuery(event.target.value)} /></label><select aria-label="Filter tool category" className="h-12 rounded-lg border border-[var(--line)] bg-[var(--surface)] px-3" value={category} onChange={event => setCategory(event.target.value)}><option value="all">All categories</option>{toolCategories.map(item => <option value={item} key={item}>{item}</option>)}</select></div>
  {selected.length >= 2 && <section className="my-10 rounded-2xl border border-[color-mix(in_srgb,var(--accent)_45%,var(--line))] bg-[color-mix(in_srgb,var(--accent)_5%,var(--surface))] p-5 md:p-7"><div className="flex items-center gap-2"><Scale className="text-[var(--accent-dark)]" /><h2 className="title-md">Compare selected tools</h2></div><p className="muted mt-2 text-sm">Select up to three. Comparison describes use and learning tradeoffs, not a universal winner.</p><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[680px] border-collapse text-left"><thead><tr><th className="border-b border-[var(--line)] p-3 text-xs uppercase tracking-wider text-[var(--muted)]">Dimension</th>{compared.map(tool => <th className="border-b border-[var(--line)] p-3" key={tool.slug}>{tool.name}</th>)}</tr></thead><tbody>{[['Purpose', (slug: string) => tools.find(t => t.slug === slug)?.description ?? ''], ['Difficulty', (slug: string) => tools.find(t => t.slug === slug)?.difficulty ?? ''], ['Best use cases', (slug: string) => tools.find(t => t.slug === slug)?.useCases.join(', ') ?? ''], ['Open source', (slug: string) => tools.find(t => t.slug === slug)?.openSource ? 'Yes' : 'No'], ['AI DevOps relevance', (slug: string) => `${tools.find(t => t.slug === slug)?.relevance ?? 0}/5`], ['Learning curve', (slug: string) => tools.find(t => t.slug === slug)?.learningCurve ?? '']].map(([label, getter]) => <tr key={label as string}><th className="border-b border-[var(--line)] p-3 text-sm">{label as string}</th>{compared.map(tool => <td className="muted border-b border-[var(--line)] p-3 text-sm leading-6" key={tool.slug}>{(getter as (slug: string) => string)(tool.slug)}</td>)}</tr>)}</tbody></table></div></section>}
  <p className="muted my-6 text-sm">{visible.length} tools · {selected.length}/3 selected for comparison</p>{visible.length ? <div className="grid gap-4 lg:grid-cols-2">{visible.map(tool => <article className="panel p-6" key={tool.slug}><div className="flex items-start justify-between gap-4"><div><span className="chip">{tool.category}</span><h2 className="mt-4 text-xl font-bold">{tool.name}</h2></div><div className="flex gap-2"><BookmarkButton compact item={{ id: tool.slug, type: 'tool', title: tool.name, path: '/tools' }} /><button className={`grid h-9 w-9 place-items-center rounded-lg border ${selected.includes(tool.slug) ? 'border-[var(--accent)] bg-[var(--accent)] text-[#031710]' : 'border-[var(--line)] bg-[var(--surface)]'}`} onClick={() => toggle(tool.slug)} disabled={!selected.includes(tool.slug) && selected.length >= 3} aria-label={`${selected.includes(tool.slug) ? 'Remove' : 'Add'} ${tool.name} ${selected.includes(tool.slug) ? 'from' : 'to'} comparison`} aria-pressed={selected.includes(tool.slug)}>{selected.includes(tool.slug) ? <Check size={17} /> : <Square size={17} />}</button></div></div><p className="muted mt-4 text-sm leading-6">{tool.description}</p><div className="mt-5 flex flex-wrap gap-2">{tool.useCases.map(useCase => <span className="chip" key={useCase}>{useCase}</span>)}</div><dl className="mt-6 grid grid-cols-3 gap-3 border-t border-[var(--line)] pt-5 text-sm"><div><dt className="muted text-xs">Open source</dt><dd className="mt-1 font-bold">{tool.openSource ? 'Yes' : 'No'}</dd></div><div><dt className="muted text-xs">Difficulty</dt><dd className="mt-1 font-bold">{tool.difficulty}</dd></div><div><dt className="muted text-xs">AI DevOps</dt><dd className="mt-1 font-bold">{tool.relevance}/5</dd></div></dl><div className="mt-5"><Rating id={`tool:${tool.slug}`} editorialRating={tool.editorialRating} /></div><a href={tool.website} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[var(--accent-dark)]">Official website <ExternalLink size={14} /></a></article>)}</div> : <div className="panel py-16 text-center"><Search className="mx-auto text-[var(--muted)]" /><h2 className="mt-4 font-bold">No tools match this filter</h2></div>}</section></PageShell>
}
